server
{
    listen 8080;
    server_name localhost webserv.local;

    # 1. FIXED: Point the global root directly to our new www folder
    root www; 
    index index.html;

    client_max_body_size 1000000;


#     # error_page 400 error_pages/400.html;
#     # error_page 403 error_pages/403.html;
#     error_page 404 error_pages/404.html;
#     # error_page 405 error_pages/405.html;
#     # error_page 413 error_pages/413.html;
#     # error_page 500 error_pages/500.html;

    # 2. Main route (Handles /, /documents, /directory1, etc.)
    location / {
        methods GET POST HEAD DELETE; # DELETE is enabled for our JS button!
        root www;
        index index.html;
        autoindex on;
    }

   location /documents {
        methods GET POST DELETE HEAD; # DELETE is enabled for our JS button!
        root www;
        autoindex on;
    }

    # 3. NEW: The Images route specifically for testing Autoindex
    location /images {
        methods GET HEAD POST DELETE;
        upload on;
        upload_store www/images;
        # Since index.html is missing inside /images, this will trigger build_autoindex!
        autoindex on; 
    }

    # --- READY FOR LATER --- 
    # (I fixed the roots for these so they are ready when we build POST and CGI)
    
    location /upload {
        methods POST GET;
        root www/upload;
        index index.html;
        client_max_body_size 5000000;
        upload on;
        upload_store www/upload/uploads;
        autoindex off;
    }

    location /old-page {
        methods GET HEAD;
        return 301 /;
    }

    location /cgi-bin {
        methods GET POST HEAD;
        root /home/cnamoune/webserv/www/cgi-bin;
        index index.py;
        cgi .py /usr/bin/python3;
        cgi .sh /bin/bash;
        autoindex off;
    }
}

server	
{
    listen 8083;
    server_name serweb;
}