server
{
    listen 8080;
    server_name localhost webserv.local;

    root www/default;
    index index.html;

    client_max_body_size 1000000;

    error_page 400 error_pages/400.html;
    error_page 403 error_pages/403.html;
    error_page 404 error_pages/404.html;
    error_page 405 error_pages/405.html;
    error_page 413 error_pages/413.html;
    error_page 500 error_pages/500.html;

    location / {
        methods GET POST DELETE HEAD;
        root www/default;
        index index.html;
        autoindex off;
    }

    location /assets {
        methods GET HEAD;
        root www/default;
        autoindex off;
    }

    location /files {
        methods GET HEAD;
        root www/files;
        autoindex on;
    }

    location /upload {
        methods POST;
        root www/upload;
        index index.html;

        client_max_body_size 5000000;

        upload on;
        upload_store www/upload/uploads;

        autoindex off;
    }

    location /old-page {
        methods GET HEAD;
        return 301 /;
    }

    location /cgi-bin {
        methods GET POST HEAD;

        root www/cgi-bin;
        index index.py;

        cgi .py /usr/bin/python3;
        cgi .php /usr/bin/php-cgi;

        autoindex off;
    }
}