server {
    listen 127.0.0.1:8080;

    root YoupiBanane;

    location / {
        methods GET;
        root www;
        index index.html;
    }

    location /post_body {
        methods POST;
        root YoupiBanane/directory;
        client_max_body_size 100;
    }

    location /directory {
        methods GET POST;
        root YoupiBanane;
        index youpi.bad_extension;
        cgi .bla ./cgi_test;
    }
}
