server {
    listen 127.0.0.1:8080;
    server_name localhost;
    root www; 
    index index.html;
    client_max_body_size 1000000;
    location /documents {
        methods GET POST DELETE HEAD; # DELETE is enabled for our JS button!
        root www;
        autoindex on;
    }
    location /images {
        methods GET HEAD POST DELETE;
        upload on;
        upload_store www/images;
        # Since index.html is missing inside /images, this will trigger build_autoindex!
        autoindex on; 
    }
}

server {
    listen 127.0.0.1:8080;
    server_name localhost2;
    root www; 
    index index.html;
    client_max_body_size 1000000;
    location / {
        methods GET; # DELETE is enabled for our JS button!
        root www;
        index index.html;
        autoindex on;
    }
    location /images {
        methods GET HEAD;
        upload on;
        upload_store www/images;
        # Since index.html is missing inside /images, this will trigger build_autoindex!
        autoindex on; 
    }
}
