server {
    listen 127.0.0.1:8080;
    listen 127.0.0.1:8081;
    server_name localhost;
}

server {
    listen 127.0.0.1:8080;
    listen 10.18.207.127:8080;
    server_name localhost2;
}

server {
    listen 127.0.0.1:8080;
    server_name site1.local;
}

server {
    listen 127.0.0.1:8080;
    server_name site2.local;
}
